### ISSUE TITLE
Challenge #2 Puzzles - kinda pointless if there's only 2 stars

### ISSUE THREAD

**Issue by daviddeutsch** [aren227/TheWitness-LockScreen#12]
First off, the new puzzle types are MUCH appreciated! Great work!

In this example from Challenge #2, though, the stars don't really add anything to the puzzle:

![Screenshot_20200826-104313](https://user-images.githubusercontent.com/630246/91283220-97698700-e78a-11ea-9202-9af7834e8526.png)

**Comment by aren227** [comment]
Yeah, but I just tried to copy it from the game.
These are the screenshots I took myself in the game.

![20200825173725_1](https://user-images.githubusercontent.com/14082448/91286811-e08cfb80-e7c9-11ea-8718-76d3844aff3c.jpg)
![20200825174151_1](https://user-images.githubusercontent.com/14082448/91286833-ea166380-e7c9-11ea-909f-083e5bdb7bcf.jpg)
![20200825180138_1](https://user-images.githubusercontent.com/14082448/91286856-f0a4db00-e7c9-11ea-8960-daab34bb0d1d.jpg)

There were always two stars.
I think this issue is rather related to Issue #10.

**Comment by daviddeutsch** [comment]
You're probably right. Although I will say that those puzzles are definitely more interesting than the ones I got so far. So perhaps there _are_ some tweaks to bump the number of interesting puzzles from that algo.
